export const CODE_BY_COUNTRY_LABEL: Record<string, string> = {
    // América
    "argentina": "AR",
    "bolivia": "BO",
    "brasil": "BR",
    "brazil": "BR",
    "canadá": "CA",
    "canada": "CA",
    "chile": "CL",
    "colombia": "CO",
    "costa rica": "CR",
    "cuba": "CU",
    "ecuador": "EC",
    "el salvador": "SV",
    "estados unidos": "US",
    "usa": "US",
    "eeuu": "US",
    "guatemala": "GT",
    "honduras": "HN",
    "méxico": "MX",
    "mexico": "MX",
    "nicaragua": "NI",
    "panamá": "PA",
    "panama": "PA",
    "paraguay": "PY",
    "perú": "PE",
    "peru": "PE",
    "república dominicana": "DO",
    "dominican republic": "DO",
    "uruguay": "UY",
    "venezuela": "VE",

    // Europa
    "albania": "AL",
    "alemania": "DE",
    "germany": "DE",
    "andorra": "AD",
    "austria": "AT",
    "bélgica": "BE",
    "belgium": "BE",
    "bielorrusia": "BY",
    "bosnia y herzegovina": "BA",
    "bulgaria": "BG",
    "chipe": "CY",
    "cyprus": "CY",
    "croacia": "HR",
    "dinamarca": "DK",
    "denmark": "DK",
    "eslovaquia": "SK",
    "eslovenia": "SI",
    "españa": "ES",
    "spain": "ES",
    "estonia": "EE",
    "finlandia": "FI",
    "finland": "FI",
    "francia": "FR",
    "france": "FR",
    "grecia": "GR",
    "greece": "GR",
    "hungría": "HU",
    "hungary": "HU",
    "irlanda": "IE",
    "ireland": "IE",
    "islandia": "IS",
    "italia": "IT",
    "italy": "IT",
    "kosovo": "XK",
    "letonia": "LV",
    "liechtenstein": "LI",
    "lituania": "LT",
    "luxemburgo": "LU",
    "malta": "MT",
    "moldavia": "MD",
    "mónaco": "MC",
    "montenegro": "ME",
    "noruega": "NO",
    "norway": "NO",
    "países bajos": "NL",
    "netherlands": "NL",
    "holanda": "NL",
    "polonia": "PL",
    "poland": "PL",
    "portugal": "PT",
    "reino unido": "GB",
    "uk": "GB",
    "united kingdom": "GB",
    "república checa": "CZ",
    "czech republic": "CZ",
    "rumanía": "RO",
    "romania": "RO",
    "rusia": "RU",
    "russia": "RU",
    "san marino": "SM",
    "serbia": "RS",
    "suecia": "SE",
    "sweden": "SE",
    "suiza": "CH",
    "switzerland": "CH",
    "ucrania": "UA",
    "ukraine": "UA",
    "vaticano": "VA",

    // Asia
    "afganistán": "AF",
    "arabia saudita": "SA",
    "saudi arabia": "SA",
    "armenia": "AM",
    "azerbaiyán": "AZ",
    "bangladés": "BD",
    "camboya": "KH",
    "china": "CN",
    "corea del sur": "KR",
    "south korea": "KR",
    "emiratos árabes unidos": "AE",
    "uae": "AE",
    "filipinas": "PH",
    "philippines": "PH",
    "georgia": "GE",
    "hong kong": "HK",
    "india": "IN",
    "indonesia": "ID",
    "irán": "IR",
    "iraq": "IQ",
    "israel": "IL",
    "japón": "JP",
    "japan": "JP",
    "jordania": "JO",
    "kazajistán": "KZ",
    "kuwait": "KW",
    "kirguistán": "KG",
    "laos": "LA",
    "líbano": "LB",
    "lebanon": "LB",
    "macao": "MO",
    "malasia": "MY",
    "maldivas": "MV",
    "mongolia": "MN",
    "myanmar": "MM",
    "nepal": "NP",
    "omán": "OM",
    "pakistán": "PK",
    "qatar": "QA",
    "singapur": "SG",
    "singapore": "SG",
    "sri lanka": "LK",
    "tailandia": "TH",
    "thailand": "TH",
    "taiwán": "TW",
    "taiwan": "TW",
    "tayikistán": "TJ",
    "turquía": "TR",
    "turkey": "TR",
    "turkmenistán": "TM",
    "uzbekistán": "UZ",
    "vietnam": "VN",
    "yemen": "YE",

    // África
    "argelia": "DZ",
    "angola": "AO",
    "benín": "BJ",
    "botsuana": "BW",
    "burkina faso": "BF",
    "burundi": "BI",
    "cabo verde": "CV",
    "camerún": "CM",
    "chad": "TD",
    "congo": "CG",
    "costa de marfil": "CI",
    "egipto": "EG",
    "egypt": "EG",
    "etiopía": "ET",
    "gabón": "GA",
    "ghana": "GH",
    "guinea": "GN",
    "kenia": "KE",
    "kenya": "KE",
    "lesoto": "LS",
    "liberia": "LR",
    "libia": "LY",
    "madagascar": "MG",
    "malaui": "MW",
    "malí": "ML",
    "marruecos": "MA",
    "morocco": "MA",
    "mauricio": "MU",
    "mauritania": "MR",
    "mozambique": "MZ",
    "namibia": "NA",
    "níger": "NE",
    "nigeria": "NG",
    "ruanda": "RW",
    "senegal": "SN",
    "seychelles": "SC",
    "sierra leona": "SL",
    "somalia": "SO",
    "sudáfrica": "ZA",
    "south africa": "ZA",
    "sudán": "SD",
    "tanzania": "TZ",
    "togo": "TG",
    "túnez": "TN",
    "tunisia": "TN",
    "uganda": "UG",
    "zambia": "ZM",
    "zimbabue": "ZW",

    // Oceanía
    "australia": "AU",
    "fiyi": "FJ",
    "guam": "GU",
    "nueva zelanda": "NZ",
    "new zealand": "NZ",
    "papúa nueva guinea": "PG",

    // Otros / Regiones
    "global": "GLOBAL",
    "asia pacifico": "ASIA",
    "asia pacific": "ASIA",
    "asia": "ASIA",
    "oceania": "OCEANIA",
    "oceanía": "OCEANIA",
    "europa": "EUROPA",
    "europe": "EUROPA",
    "africa": "AFRICA",
    "áfrica": "AFRICA",
    "américa del sur": "SOUTH_AMERICA",
    "south america": "SOUTH_AMERICA",
    "centro-sur-america": "CENTRO-SUR-AMERICA",
    "centro sur america": "CENTRO-SUR-AMERICA",
    "centroamérica": "CENTRO-SUR-AMERICA",
    "central america": "CENTRO-SUR-AMERICA",
    "latam": "LATAM",
    "latinoamérica": "LATAM",
    "américa del norte": "NORTEAMERICA",
    "north america": "NORTEAMERICA",
    "norteamerica": "NORTEAMERICA",
    "norteamérica": "NORTEAMERICA",
    "oriente medio": "MIDDLE_EAST",
    "middle east": "MIDDLE_EAST",
    "caribe": "CARIBBEAN",
    "caribbean": "CARIBBEAN",
};
